/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  printWidth: 80,
  bracketSpacing: true,
  arrowParens: "always",
  quoteProps: "consistent",

  importOrder: [
    "^react$",
    "^react-dom$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/components/ui/(.*)$",
    "",
    "^@/components/shared/(.*)$",
    "",
    "^@/components/(.*)$",
    "",
    "^@/lib/(.*)$",
    "^@/utils/(.*)$",
    "^@/constants$",
    "^@/data/(.*)$",
    "^@/api$",
    "^@/api/(.*)$",
    "",
    "^@/hooks$",
    "^@/hooks/(.*)$",
    "^@/store$",
    "^@/store/(.*)$",
    "",
    "^@/types$",
    "^@/types/(.*)$",
    "^types$",
    "",
    "^@/styles/(.*)$",
    "^@/config/(.*)$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],

  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],

  tailwindFunctions: ["cn", "cva"],
};
